services:
    stadline_js_extension.twig.functions_extension:
        class: StadLine\JsExtensionBundle\Twig\FunctionsExtension
        tags:
            - { name: twig.extension }
        arguments: [ %kernel.root_dir% ]
        calls :
            - [setSerializer, [@jms_serializer]]